### ISSUE TITLE
[Doc] LIBRG_LAST_EVENT should be last, not first

### ISSUE THREAD

**Issue by TheAifam5** [librg/librg#13]
Hey,

In the code documentation, the fist enum item is marked as “last” with “LIBRG_LAST_EVENT”.
Is that intended?

I think that should be moved to Line 390.

Related code:
https://github.com/librg/librg/blob/2f2dfd783bff7dceadf03dc7e514012a05822f50/include/librg.h#L388

Regards,
TheAifam5

**Comment by inlife** [comment]
Yes, that is intended. The point of that for a final user to start his enum from a valid, non-colliding number coming from the last enum value. Think of it as an "extend" for the enum.
