### ISSUE TITLE
Add result to librg_init

### ISSUE THREAD

**Issue by markatk** [librg/librg#14]
When initializing enet fails (for example due to an already bound port on server side), the `librg_init` function does not give any result about it (except from the assert message). It would be nice to change the function to return a result or state so programs can do proper error management.

**Comment by markatk** [comment]
I am sorry, I messed up the function. The port failure is happening in `librg_network_start`. But nevertheless both functions (and i think some more others) could benefit from returned results.

**Comment by inlife** [comment]
i agree, those additions would be quite useful
