### ISSUE TITLE
Disconnected client entities trigger entity update once

### ISSUE THREAD

**Issue by markatk** [librg/librg#21]
When a client disconnects (or timeouts, doesn't matter) from the server there is one entity update event triggered **after** the disconnect event. 

```
...
Update entity 1 for client 1773685128
Update entity 0 for client 647576079
Update entity 1 for client 1773685128
Update entity 0 for client 647576079
Update entity 1 for client 1773685128
Update entity 0 for client 647576079
Update entity 1 for client 1773685128
Update entity 0 for client 647576079
client 647576079 disconnected
Update entity 1 for client 1773685128
Update entity 0 for client 647576079
```

**Comment by inlife** [comment]
interesting
i'm assuming that is happening because of entity destruction on the server-side is not immediate, but rather it allows for one last tick to happen before entity destroy will be sent, however in this case, i'm not sure if that is the reason

**Comment by inlife** [comment]
hey @markatk 
could you try the lastest version from master, to see if it the solves issue for you?

**Comment by markatk** [comment]
As far as my testing goes it seems to be fixed

**Comment by inlife** [comment]
oh, that is great news
