### ISSUE TITLE
Noob question: How does a single header library not cause mutiple symbol definitions?

### ISSUE THREAD

**Issue by Dan782** [librg/librg#22]
Please excuse my naivety but I've never encountered single-header libraries till now.

I think this is a very nice library but I am rather confused about how I would go about using it.

I understand that if all the functions are 'inline' then there really isn't any true symbol definitions that could collide when linking multiple object files... But looking at the source of librg I am seeing functions which do not have any inline keyword specified anywhere, for example:

```
u64 librg_event_add(librg_ctx *ctx, u64 id, librg_event_cb callback) {
        librg_assert(ctx);
        librg_event_block *block = librg_event_pool_get(&ctx->events, id);

        if (!block) {
            librg_event_block arr;
            zpl_array_init(arr, ctx->allocator);
            librg_event_pool_set(&ctx->events, id, arr);
            block = librg_event_pool_get(&ctx->events, id);
        }

        u64 offset = zpl_array_count(block);
        zpl_array_append(*block, callback);
        return offset;
}
```

I assume that there must be some non-conventional use of this header necessary to get it working otherwise if I were to include this file in multiple C files and then link them together I would get linker errors for multiple symbol definitions with the same name, wouldn't I?

Sorry if this is the wrong place to ask this question but I wasn't sure where else would be appropriate.

Also, why the #if 1 statements wrapping sections of code? Those seem pointless and I can't grasp what their purpose would be, other than to manually toggle the compilation of specific sections... But wouldn't that be better achieved by using actual ```#ifdef SOME_MACRO``` switches where all the switches can be listed at the top of the file for ease of toggling?

**Comment by inlife** [comment]
Hey @Dan782 

Ok, so regarding the collisions. As you might've noticed in the top of the library you see these instructions: https://github.com/librg/librg/blob/master/include/librg.h#L4-L8

That means that if your projects consist of let's say 20 c/cpp files, and you need to include librg to 8 of them, you can freely do that, however, you would need to define `LIBRG_IMPLEMENTATION` in exactly one of those c/cpp files. That definition will add the C part of symbols, and embed them into your program. Same principle usually applies to other single-header libraries.

Regarding the #if 1 switches, they were mostly used by me while developing the code, for quick folding. So I could fold-n-hide parts of the code I didn't need at that moment.

**Comment by Dan782** [comment]
Oh jeez I feel really stupid now having missed that obvious set of instructions, I also did see the LIBRG_IMPLEMENTATION macro while reading the code but for some reason I must have misidentified the endif and thought the macro only protected a few functions.

Well this has been extremely informative and you have definitely incited some interest in using the library in one of my projects.

Thanks for all the help and maybe after I get to know the library I can give something back to the project :)

**Comment by inlife** [comment]
Great to hear, cheers!
