### ISSUE TITLE
Your are using eNet code which does not exist 

### ISSUE THREAD

**Issue by meiry** [librg/librg#26]
This not exist in eNet code (ENET_EVENT_TYPE_DISCONNECT_TIMEOUT)
```
case ENET_EVENT_TYPE_DISCONNECT_TIMEOUT: {                                                                                                                                                                                 
 
```

and this function : 
```
enet_packet_create_offset
```

using latest version of eNet from github

**Comment by inlife** [comment]
Hello,

As stated in the readme, we are using our fork of ENet: https://github.com/zpl-c/enet

**Comment by meiry** [comment]
Thanks for the quick replay , 
as im reading the README again , i do see you mentioned this in the Description.
but there is no link to your modified version of enet ....
maybe highlight it more . 
can you please also explain what is bean modified and why ?
thanks allot

**Comment by inlife** [comment]
It is a good suggestion indeed, I wonder why didn't we do that right from the start.
