### ISSUE TITLE
Sending user inputs in server-authoritative model

### ISSUE THREAD

**Issue by bullno1** [librg/librg#7]
What is the intended way to send inputs from client to server using this library?
By inputs I mean things like key held, look direction... They are sampled and sent at regular intervals. I can think of two ways:

Using message is one. However, messages are always sent as reliable which is not very optimal since client will keep sending (a buffer of) inputs anyway.

Another method is to create a "controller" entity and let client stream it. The data of that entity will be the client's inputs. This feels a bit weird.

Ideally, should there be a way to send unreliable messages? If I were to add another parameter, the number of `librg_message_send` functions would double though.

**Comment by bullno1** [comment]
From Discord:

> 1. Yes, you are right, the intended way for sending input in authoritative model is via messages. And I think reliability for player inputs is something that you would actually be happy to have. Since it's something that always needs to be delivered.
> Regarding the message sending functions, channels and reliability flags. For some time now i'm considering some API changes to provide more functionality to those areas, however I'm still not sure about the design. If you have any ideas regarding how the message sending API should look like - I would be glad to see them.

> 2. Well, if entities are in the range of the client entity, the idea is that they all will be attempted to be sent, unless you manually decide to prevent sending for some (or all) of them. You can use method librg_event_reject(&event), to prevent any of the librg_entity_create, entity_update or entity_remove calls for the entity flow.

> And yes, librg relies on enet packet fragmentation to deliver the given message.
Also, worth mentioning, entity_create and entity_remove type messages will be always delivered via reliable channel,
while entity_update is  being delivered only via unreliable channel atm, which makes it something that needs to be sent more often and keeping in mind the fact that data that is being sent might or might not come to the destination. 

> While from the other side if you want to be sure that data that you've send is gonna be delivered for a particular entity, you would use message.
I also think the reliability/unreliability should be user defined/supported by API, in the future at least.

> And quick notion about rejection, yes as i mentioned above you will be responsible about the rejection if you dont wanna send non-updated data, however keep in mind since the update stuff is unreliable i would recommend building an algo that would be still sending the updates occasionally with slow rate (mostly rejecting), and after a change it would behave like a wave, and gradually decrease amount of sendings per particlar entity. Same applies for both server and client (if you are using the client control stuff)

**Comment by inlife** [comment]
Hey @bullno1 please check out the commit:
https://github.com/librg/librg/commit/e53aed5e9ed7e1bb97ac8969458858a10af497e0

I've implemented the new proposed message interface
